/* bench-prompts.js - the prompt set, frozen, so a live run and an offline
 * one are the same experiment.
 *
 * 100 prompts, 5 sites, twenty each, hand-written against the control
 * list every page really carries. 30 of them are chains - two or three
 * steps in one sentence - where the two sets this replaces had three
 * between them across two hundred and twenty-three prompts.
 *
 * Nothing in here can be answered by matching a printed label. The set this
 * replaces was enumerated from each page's own controls, so most of it read
 * "click NDMC" or "click tag: Drought Index" - a footer logo asked for by
 * name, which is exactly what the name matcher exists to catch. On one site
 * three of twenty-four prompts reached the model.
 *
 * `offline` on each row is what the grounding layer alone did with this
 * exact prompt, the model switched off, against the captured page in
 * research/live-scoring/pages. 70 of 100 are false: that is the share of
 * the set that has no answer without a model, and it is the reason to
 * believe a live number measures the system rather than the matcher.
 *
 * Read the offline column with jsdom's limits in mind - it applies no
 * stylesheet and does no layout, so CSS-hidden menus are wide open there
 * and a browser is strictly harder. It is a floor, not a forecast.
 *
 * And it is weaker still on the reading rows. Offline, a reading prompt
 * passes when the page yields more than sixty characters to summarise - it
 * checks that there is something to read, not that anything explained it,
 * because explaining is the model's job and the model is off. All fifteen
 * read `offline: true` for that reason and none of them should be counted
 * as answered without a model. The live run is the only thing that says
 * whether those fifteen work.
 *
 * kinds: chain | paraphrase | vocabulary | world-knowledge | reading
 *        | refusal | judgment
 *
 * Generated by research/live-scoring/build-bench-set.js from
 * research/live-scoring/submission-set.js, which is the hand-written
 * source and the file to edit.
 */
globalThis.WC_BENCH_PROMPTS = {
 "usgs": {
  "url": "https://waterdata.usgs.gov/monitoring-location/01646500/",
  "note": "Potomac River at Little Falls Pump Station, DC. Discharge and gage height.",
  "prompts": [
   {"say":"set it to thirty days and then show the legend","kind":"chain","on":"Show legend","want":{"clicked":"Show legend"},"offline":false},
   {"say":"give me a year of record, then open the tabular view","kind":"chain","on":"View tabular data","want":{"clicked":"tabular data"},"offline":false},
   {"say":"plot the gage height and then overlay the same span from last year","kind":"chain","on":"Data for same time span in prior year","want":{"clicked":"prior year"},"offline":false},
   {"say":"switch the vertical axis to logarithmic and then narrow the window to a week","kind":"chain","on":"7 days","want":{"clicked":"7 days"},"offline":false},
   {"say":"expand all the data collections and then show me where this gauge sits","kind":"chain","on":"Show location details","want":{"clicked":["location details","Site Location"]},"offline":false},
   {"say":"open the related graphs and then take me to the water year summary","kind":"chain","on":"Water Year Summary","want":{"clicked":"Water Year Summary"},"offline":true},
   {"say":"narrow this down to just the past week","kind":"paraphrase","on":"7 days","want":{"clicked":"7 days"},"offline":false},
   {"say":"I want the whole record for the last twelve months","kind":"paraphrase","on":"1 year","want":{"clicked":"1 year"},"offline":false},
   {"say":"clean up everything printed below the plot","kind":"paraphrase","on":"Hide graph details","want":{"clicked":"graph details"},"offline":false},
   {"say":"give me these readings as raw rows instead of a picture","kind":"paraphrase","on":"View tabular data","want":{"clicked":"tabular data"},"offline":false},
   {"say":"I need this file saved on my computer","kind":"paraphrase","on":"Download data","want":{"clicked":"Download data"},"offline":false},
   {"say":"plot the stage rather than the flow","kind":"vocabulary","on":"Graph Gage height, feet","want":{"clicked":"Gage height"},"offline":false},
   {"say":"show me discharge in cfs","kind":"vocabulary","on":"Graph Discharge, cubic feet per second","want":{"clicked":"Discharge"},"offline":false},
   {"say":"use a scale that keeps the low readings legible","kind":"world-knowledge","on":"Log","want":{"clicked":"Log"},"offline":false},
   {"say":"this is one gauge of thousands, take me to the map of all of them","kind":"world-knowledge","on":"National Water Dashboard","want":{"clicked":"National Water Dashboard"},"offline":false},
   {"say":"what is this river doing right now, in plain terms","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"explain what the two plotted series on this page actually measure","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"is the flow shown here high or low for this time of year","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"export this chart as a powerpoint slide","kind":"refusal","on":null,"want":{"refuse":true},"offline":true},
   {"say":"if the gage height is above three feet show me a year of data, otherwise show me a week","kind":"judgment","on":"7 days","want":{"clicked":"days"},"offline":false}
  ]
 },
 "droughtmap": {
  "url": "https://droughtmonitor.unl.edu/CurrentMap.aspx",
  "note": "U.S. Drought Monitor, current national map. Weekly, retrospective.",
  "prompts": [
   {"say":"open the archive and then play it back as an animation","kind":"chain","on":"Animations","want":{"clicked":"Animations"},"offline":false},
   {"say":"pull up the statistics by threshold and then download those numbers","kind":"chain","on":"Data Download","want":{"clicked":"Data Download"},"offline":false},
   {"say":"show me the West, then put it side by side with last week","kind":"chain","on":"Compare Two Weeks","want":{"clicked":"Compare Two Weeks"},"offline":false},
   {"say":"open the time series and then give me the bar chart form of it","kind":"chain","on":"Bar Chart","want":{"clicked":"Bar Chart"},"offline":true},
   {"say":"find the eligibility tool for farmers, then the agriculture page","kind":"chain","on":"Ag in Drought","want":{"clicked":"Ag in Drought"},"offline":false},
   {"say":"switch into Spanish and then bring me back to this week's map","kind":"chain","on":"Current","want":{"clicked":"Current"},"offline":false},
   {"say":"I am colourblind, make this readable","kind":"paraphrase","on":"View grayscale version of the map","want":{"clicked":"grayscale"},"offline":false},
   {"say":"how do they decide what counts as D3","kind":"paraphrase","on":"Drought Classification","want":{"clicked":"Classification"},"offline":false},
   {"say":"how many people are living through this","kind":"paraphrase","on":"Population Statistics","want":{"clicked":"Population"},"offline":false},
   {"say":"who do I email about a mistake on this map","kind":"paraphrase","on":"Contact Us","want":{"clicked":"Contact"},"offline":false},
   {"say":"let me know by email every time this updates","kind":"paraphrase","on":"Drought Alert Request","want":{"clicked":"Alert Request"},"offline":false},
   {"say":"show me the DSCI","kind":"vocabulary","on":"Drought Severity and Coverage Index","want":{"clicked":"Severity and Coverage"},"offline":false},
   {"say":"where are the shapefiles","kind":"vocabulary","on":"GIS Data","want":{"clicked":"GIS Data"},"offline":true},
   {"say":"just the lower forty eight","kind":"world-knowledge","on":"Continental U.S.","want":{"clicked":"Continental"},"offline":false},
   {"say":"I need the one that covers Alaska and Hawaii as well","kind":"world-knowledge","on":"OCONUS Drought Status","want":{"clicked":"OCONUS"},"offline":false},
   {"say":"what share of the country is in drought right now","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"explain in plain language what this week's map is showing","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"which part of the country is worst off on this map","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"show me tomorrow's drought map","kind":"refusal","on":null,"want":{"refuse":true},"offline":false},
   {"say":"if the West is drier than the Midwest open the West, otherwise open the Midwest","kind":"judgment","on":"West","want":{"clicked":"West"},"offline":false}
  ]
 },
 "noaa": {
  "url": "https://water.noaa.gov/",
  "note": "National Water Prediction Service landing map.",
  "prompts": [
   {"say":"open the layer list and then zoom the map in","kind":"chain","on":"Zoom in","want":{"clicked":"Zoom in"},"offline":false},
   {"say":"find the daily briefing and then show me its key messages","kind":"chain","on":"Key Messages","want":{"clicked":"Key Messages"},"offline":true},
   {"say":"check the snow analysis first, then the river ice","kind":"chain","on":"River Ice Surveillance","want":{"clicked":"River Ice"},"offline":false},
   {"say":"look up the drought information and then jump to the national portal for it","kind":"chain","on":"Drought.gov Portal","want":{"clicked":"Portal"},"offline":false},
   {"say":"show me where the data lives, then the API documentation","kind":"chain","on":"NWPS APIs","want":{"clicked":"NWPS APIs"},"offline":false},
   {"say":"open the flood hazard outlook and then the safety resources","kind":"chain","on":"Flood and Safety Resources","want":{"clicked":"Safety Resources"},"offline":true},
   {"say":"how much rain has already fallen","kind":"paraphrase","on":"Past Precipitation Estimates","want":{"clicked":"Precipitation Estimates"},"offline":false},
   {"say":"which rivers are running high at the moment","kind":"paraphrase","on":"Rivers-at-a-Glance","want":{"clicked":"Rivers-at-a-Glance"},"offline":false},
   {"say":"what will the water do over the next few months","kind":"paraphrase","on":"Long Range Outlook","want":{"clicked":"Long Range Outlook"},"offline":false},
   {"say":"show me how deep the water would get on my street","kind":"paraphrase","on":"Flood Inundation Mapping (FIM)","want":{"clicked":"Inundation"},"offline":false},
   {"say":"I cannot read these charts, is there an explainer","kind":"paraphrase","on":"Hydrograph Information","want":{"clicked":"Hydrograph"},"offline":false},
   {"say":"pull up HEFS","kind":"vocabulary","on":"Hydrologic Ensemble Forecast System (HEFS)","want":{"clicked":"Ensemble"},"offline":false},
   {"say":"what does Atlas 14 say","kind":"vocabulary","on":"Current Standard: NOAA Atlas 14","want":{"clicked":"Atlas 14"},"offline":false},
   {"say":"who issues the forecast for my local river basin","kind":"world-knowledge","on":"River Forecast Centers","want":{"clicked":"Forecast Centers"},"offline":false},
   {"say":"I want the simulation that covers every stream in the country","kind":"world-knowledge","on":"National Water Model","want":{"clicked":"National Water Model"},"offline":false},
   {"say":"what is this map actually showing me","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"summarise the national water situation as it stands","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"are there any river flood warnings in effect right now","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"give me the ocean tide tables for Boston harbour","kind":"refusal","on":null,"want":{"refuse":true},"offline":true},
   {"say":"if a significant river flood outlook is posted open it, otherwise open the hydrologic discussion","kind":"judgment","on":"Significant River Flood Outlook","want":{"clicked":"Outlook"},"offline":true}
  ]
 },
 "weather": {
  "url": "https://www.weather.gov/",
  "note": "National Weather Service home page. Live alert links change hourly.",
  "prompts": [
   {"say":"open the radar and then switch it to the low bandwidth version","kind":"chain","on":"Standard Radar (Low Bandwidth)","want":{"clicked":"Low Bandwidth"},"offline":false},
   {"say":"check the aviation forecast, then the one for boats","kind":"chain","on":"Marine","want":{"clicked":"Marine"},"offline":false},
   {"say":"open the education section and then find the glossary in it","kind":"chain","on":"Glossary","want":{"clicked":"Glossary"},"offline":false},
   {"say":"show me the satellite view and then the air quality","kind":"chain","on":"AIR QUALITY","want":{"clicked":"AIR QUALITY"},"offline":true},
   {"say":"go to the river and rainfall page, then the long range forecasts","kind":"chain","on":"Long Range Forecasts","want":{"clicked":"Long Range"},"offline":true},
   {"say":"find the storm spotter programme and then the preparedness certification","kind":"chain","on":"StormReady","want":{"clicked":"StormReady"},"offline":false},
   {"say":"I am taking a small plane up tomorrow","kind":"paraphrase","on":"Aviation","want":{"clicked":"Aviation"},"offline":false},
   {"say":"is it safe to take the boat out","kind":"paraphrase","on":"Marine","want":{"clicked":"Marine"},"offline":false},
   {"say":"will it be light out when I leave at six","kind":"paraphrase","on":"Sunrise/Sunset","want":{"clicked":"Sunrise"},"offline":false},
   {"say":"what do these warning terms actually mean","kind":"paraphrase","on":"Glossary","want":{"clicked":"Glossary"},"offline":false},
   {"say":"I want the receiver that wakes me up for emergencies","kind":"paraphrase","on":"NOAA Weather Radio","want":{"clicked":"Weather Radio"},"offline":false},
   {"say":"show me the CPC outlook","kind":"vocabulary","on":"Climate Prediction","want":{"clicked":"Climate Prediction"},"offline":false},
   {"say":"where do I sign up for SKYWARN","kind":"vocabulary","on":"SKYWARN Storm Spotters","want":{"clicked":"SKYWARN"},"offline":false},
   {"say":"solar flares knock out my GPS, where would I check on that","kind":"world-knowledge","on":"Space Weather","want":{"clicked":"Space Weather"},"offline":false},
   {"say":"my county wants the tornado preparedness certification","kind":"world-knowledge","on":"StormReady","want":{"clicked":"StormReady"},"offline":false},
   {"say":"what warnings are active across the country right now","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"explain what this page is telling me about today's weather","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"which of the current alerts is the most serious","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"give me the ten day forecast for London","kind":"refusal","on":null,"want":{"refuse":true},"offline":false},
   {"say":"if a hurricane warning is up open hurricanes, otherwise open severe weather","kind":"judgment","on":"Severe Weather","want":{"clicked":"Weather"},"offline":true}
  ]
 },
 "drought": {
  "url": "https://www.drought.gov/",
  "note": "NIDIS national drought portal.",
  "prompts": [
   {"say":"pick California and then show me the outlook for the coming months","kind":"chain","on":"Outlooks and Forecasts","want":{"clicked":"Outlooks"},"offline":false},
   {"say":"open agriculture and then the most recent report on it","kind":"chain","on":"Featured Reports and Outlooks","want":{"clicked":"Featured Reports"},"offline":false},
   {"say":"show soil moisture first and then the vegetation view","kind":"chain","on":"Vegetation","want":{"clicked":"Vegetation"},"offline":true},
   {"say":"find the tribal page and then the engagement information under it","kind":"chain","on":"Tribal Engagement","want":{"clicked":"Tribal Engagement"},"offline":false},
   {"say":"go to the Southern Plains and then pull up conditions there now","kind":"chain","on":"Current Conditions","want":{"clicked":"Current Conditions"},"offline":false},
   {"say":"open the basics and then explain the difference between the short and long term kind","kind":"chain","on":"Short-Term vs Long-Term Drought","want":{"clicked":"Short-Term"},"offline":false},
   {"say":"what damage is this causing","kind":"paraphrase","on":"Drought Impacts","want":{"clicked":"Impacts"},"offline":false},
   {"say":"I want tree ring records going back centuries","kind":"paraphrase","on":"Paleoclimate","want":{"clicked":"Paleoclimate"},"offline":false},
   {"say":"is my tap at risk","kind":"paraphrase","on":"Water Utilities","want":{"clicked":"Water Utilities"},"offline":false},
   {"say":"how does this end up making people ill","kind":"paraphrase","on":"Public Health","want":{"clicked":"Public Health"},"offline":false},
   {"say":"is there money going for research into this","kind":"paraphrase","on":"Funding Opportunities","want":{"clicked":"Funding"},"offline":false},
   {"say":"show me flash drought","kind":"vocabulary","on":"Flash Drought","want":{"clicked":"Flash Drought"},"offline":true},
   {"say":"what is NIDIS","kind":"vocabulary","on":"About NIDIS","want":{"clicked":"NIDIS"},"offline":false},
   {"say":"the states that grow most of the country's corn","kind":"world-knowledge","on":"Midwest","want":{"clicked":"Midwest"},"offline":false},
   {"say":"I teach fifth grade and need something for the classroom","kind":"world-knowledge","on":"Resources for Teachers and Students","want":{"clicked":"Teachers"},"offline":false},
   {"say":"summarise the national drought picture as it stands","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"explain how much of the country this is affecting","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"which sector does this page say is hit hardest","kind":"reading","on":null,"want":{"read":true},"offline":true},
   {"say":"file a federal disaster claim for my farm from here","kind":"refusal","on":null,"want":{"refuse":true},"offline":true},
   {"say":"if California-Nevada is in drought open that region, otherwise open the national view","kind":"judgment","on":"California-Nevada","want":{"clicked":"California"},"offline":true}
  ]
 }
};
